version: "3.9"

services:
  mydb:
    container_name: mydb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_TK_PW}
    volumes:
      - mkb-mount:/var/lib/mysql
    networks:
      - mkb

  mkb:
    build: .
    container_name: mkb
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mkb

volumes:
  mkb-mount:

networks:
  mkb: